apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: bb-env
  name: bb-env
spec:
  containers:
  - command:
    - sh
    - -c
    - "sleep 1000"
    env:
      - name: PLANET
        value: blue
    image: busybox
    name: bb-env
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
